export const canvasEvents = {
  ZOOM_IN: "ZOOM_IN",
  ZOOM_OUT: "ZOOM_OUT",
  MOUSE_DOWN: "MOUSE_DOWN",
  MOVE_ELEMENT: "MOVE_ELEMENT",
  MOVED_ELEMENT_OUTSIDE: "MOVED_ELEMENT_OUTSIDE",
  RENDER_SCENE: "RENDER",
};
